{% set name = "pyflct" %}
{% set version = "0.2.2.post0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 75b888618636d9ccd3bfbbbbec64a50414c582137d5aec7f93dfc7e3e8e1d17e

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - python
    - pip
    - numpy
    - fftw
    - extension-helpers
    - setuptools_scm
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pytest
  imports:
    - pyflct
    - pyflct.utils
  commands:
    - python -m pytest --pyargs pyflct

about:
  home: https://github.com/sunpy/pyflct
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE.rst
  summary: A Python wrapper for Fourier Local Correlation Tracking
  description: |
    pyflct is Python wrapper that allows a user to perform Fourier Local Correlation Tracking (FLCT).
    The C-based implementation of the FLCT algorithm is developed by George H. Fisher and Brian T. Welsch
  doc_url: https://pyflct.readthedocs.io/en/latest/
  dev_url: https://github.com/sunpy/pyflct

extra:
  recipe-maintainers:
    - cadair
    - nabobalis
