{% set name = "pyflct" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 81c8f7deb53664d0ad29e54bbe0509d1312d9e3b6c8b7712e7c32347548064f7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<310]

requirements:
  build:
    - {{compiler('c')}}
  host:
    - cython
    - python
    - pip
    - numpy
    - fftw
    - extension-helpers
    - setuptools
    - setuptools-scm
  run:
    - python
    - numpy
    - packaging

test:
  requires:
    - pytest
  imports:
    - pyflct
    - pyflct.utils
  commands:
    - python -m pytest --pyargs pyflct

about:
  home: https://github.com/sunpy/pyflct
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE.rst
  summary: A Python wrapper for Fourier Local Correlation Tracking
  description: |
    pyflct is Python wrapper that allows a user to perform Fourier Local Correlation Tracking (FLCT).
    The C-based implementation of the FLCT algorithm is developed by George H. Fisher and Brian T. Welsch
  doc_url: https://pyflct.readthedocs.io/en/latest/
  dev_url: https://github.com/sunpy/pyflct

extra:
  recipe-maintainers:
    - cadair
    - nabobalis
